'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Rainmeter_Shortcut_Creator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property background() As String
            Get
                Return ResourceManager.GetString("background", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Rainmeter]
        '''OnRefreshAction=!ZPos &quot;-2&quot;
        '''AlwaysOnTop=-2
        '''
        '''[Wallpaper]
        '''Meter = Image
        '''ImageName = @Background@
        '''MouseOverAction=[!ZPos &quot;-2&quot;].
        '''</summary>
        Friend ReadOnly Property background1() As String
            Get
                Return ResourceManager.GetString("background1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Rainmeter]
        '''Update=1000
        '''AccurateText=1
        '''DynamicWindowSize=1
        '''AlwaysOnTop=0
        '''@ContextMenuAddOn@
        '''
        '''[Metadata]
        '''Name=@ProcessName@
        '''
        '''[On]
        '''Meter=Image
        '''ImageName=@Icon@
        '''X=0
        '''Y=0
        '''SolidColor=0, 0, 0, 1
        '''@KillTask@
        '''Group=On
        '''PreserveAspectRatio=2
        '''AntiAlias=1
        '''@ShowBackground@
        '''
        '''[Off]
        '''Meter=Image
        '''ImageName=@Icon@
        '''X=0
        '''Y=0
        '''SolidColor=0, 0, 0, 1
        '''ImageAlpha=150
        '''LeftMouseUpAction=!Execute [&quot;C:\Windows\System32\schtasks.exe&quot; &quot;/run&quot; &quot;/tn&quot; &quot;@StartTaskName@&quot;]
        '''Group=Off
        '''Hidden=1
        '''PreserveAspectRatio=2
        '''Ant [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property baseMonitor() As String
            Get
                Return ResourceManager.GetString("baseMonitor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Rainmeter]
        '''Update=1000
        '''AccurateText=1
        '''DynamicWindowSize=1
        '''AlwaysOnTop=0
        '''@ContextMenuAddOn@
        '''
        '''[Metadata]
        '''Name=@ProcessName@
        '''
        '''[on]
        '''Meter=Image
        '''ImageName=@Icon@
        '''X=0
        '''Y=0
        '''SolidColor=0, 0, 0, 1
        '''LeftMouseUpAction=!Execute [&quot;C:\Windows\System32\schtasks.exe&quot; &quot;/run&quot; &quot;/tn&quot; &quot;@StartTaskName@&quot;]
        '''Group=on
        '''PreserveAspectRatio=2
        '''AntiAlias=1
        '''@ShowBackground@.
        '''</summary>
        Friend ReadOnly Property baseNoMonitor() As String
            Get
                Return ResourceManager.GetString("baseNoMonitor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ContextTitle=Open Folder
        '''ContextAction=!Execute[&quot;explorer&quot; &quot;@ApplicationPath@&quot;].
        '''</summary>
        Friend ReadOnly Property ContextMenuAddOn() As String
            Get
                Return ResourceManager.GetString("ContextMenuAddOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LeftMouseUpAction=!Execute [&quot;C:\Windows\System32\schtasks.exe&quot; &quot;/run&quot; &quot;/tn&quot; &quot;@StopTaskName@&quot;].
        '''</summary>
        Friend ReadOnly Property KillTask() As String
            Get
                Return ResourceManager.GetString("KillTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MouseOverAction=[!ActivateConfig &quot;@SkinPath@\Background&quot; &quot;background.ini&quot;]
        '''MouseLeaveAction=[!DeactivateConfig &quot;@SkinPath@\Background&quot; &quot;background.ini&quot;].
        '''</summary>
        Friend ReadOnly Property ShowBackground() As String
            Get
                Return ResourceManager.GetString("ShowBackground", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
